import { Geist, Geist_Mono ,Poppins,Volkhov} from "next/font/google";

import "./globals.css";

const volkhov = Volkhov({
  weight: ["400","700"], // Ajoute un poids spécifique ici
  variable: "--font-volkhov",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400","600"], // Ajoute un poids spécifique ici
  variable: "--font-poppins",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
